### ISSUE TITLE
No lights or collsion lights

### ISSUE THREAD

**Issue by maurice825** [deltagamer/DEGA_Merlins#2]
Hi Deltagamer,

I noticed that there are no lights or collision lights.
Was this on purpose i.e. not ready yet?

Thanks!
Maurice

**Comment by OpforStretch** [comment]
Hey maurice,

Thanks for letting me know. The Wildcats also had this problem but was fixed in the recent release. This issue should also be fixed in the next version.

Cheers,
Delta.

**Comment by maurice825** [comment]
Thank you, I'll let my community know we can start using the merlins, since there is an update upcoming!
